// <auto-generated />
namespace M17E_TrabalhoModelo_2022_2023.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class utilizadores : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(utilizadores));
        
        string IMigrationMetadata.Id
        {
            get { return "202302230924563_utilizadores"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
